### PR TITLE
print git clone errors

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by timj — CHANGES_REQUESTED** [review]
I'd like more detail in the commit message for the change relating to trapping for cloning errors. Are you now trying to clone all the repos and then reporting the failures rather than just the first failure?

The travis change seems to include formatting changes as well as a fix. Is the real fix here the `-2` and the display of the commit sha1? Please split up the commit.

**Comment by jhoblitt** [comment]
@timj At present, `git` error output during cloning is *never* reported.  There is no change in workflow logic in this PR. `git` error messages are accumulated on a per product basis and will be printed IF `lsst_build` gives up on trying to clone a product.

**Comment by timj** [comment]
@jhoblitt okay. The travis commit does need to be cleaned up.

**Comment by jhoblitt** [comment]
@timj The changes to {{.travis.yml}} have been split up.

**Review by timj — APPROVED** [review]

**Pull request merged**
